spring.application.name=webapi

# Nombre por defecto del entorno y puerto
app.instance.name=${APP_INSTANCE_NAME:BLUE}
server.port=${PORT:8080}

# Exponer Actuator Health
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always