name: Java CI with Maven (Features & PRs)

on:
  push:
    branches:
      - "feature/**"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build, Test and Code Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      # 1. Build
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      # 2. Run tests with Maven
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml

      # 3. Run Code Coverage with Maven
      - name: Run Code Coverage with Maven
        run: mvn -B test jacoco:report --file pom.xml

      # 4. Publicar Reporte de Pruebas
      - name: Publish Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report-artifact
          path: target/surefire-reports/

      # 5. Publicar Reporte de Cobertura JaCoCo
      - name: Publish Code Coverage Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: code-coverage-report-artifact
          path: target/site/jacoco/

      # 6. Publicar JAR temporal
      - name: Publish JAR
        uses: actions/upload-artifact@v4
        with:
          name: webapi-artifact
          path: target/*.jar